### ISSUE TITLE
test-types drift: TS2353 on subagent-announce.{continuation-drain,silent-wake}.test.ts — `getRuntimeConfig` not in `DeliveryRuntimeMockOptions`

### ISSUE THREAD

**Issue by cael-dandelion-cult** [karmaterminal/openclaw#519]
**Surface**: `pnpm tsgo:test` (`check-test-types` job) fails with TS2353 on two test files in `src/agents/`.

```
src/agents/subagent-announce.continuation-drain.test.ts(90,5): error TS2353: Object literal may only specify known properties, and 'getRuntimeConfig' does not exist in type 'DeliveryRuntimeMockOptions'.
src/agents/subagent-announce.silent-wake.test.ts(99,5): error TS2353: Object literal may only specify known properties, and 'getRuntimeConfig' does not exist in type 'DeliveryRuntimeMockOptions'.
```

**Root cause hypothesis**: `DeliveryRuntimeMockOptions` type drifted (likely a property renamed or removed) without updating the two consuming test files. `getRuntimeConfig` is a leftover key on the mock-option literals.

**Status**:
- Preexisting on `frond-scribe/325-canonical2-pathB-rebase` v3 head (`a5c572585e`) — not introduced by PR #515 wave.
- Confirmed by 🌻 in PR #515 review (escalation comment `4362452945`): *"Looks like base/canonical2 drift, not v5's wiring."*
- All four princes agreed scope-disjoint from band-restoration; PR #515 self-merged via `--admin` override on this basis.

**Fix shape**:
1. Locate `DeliveryRuntimeMockOptions` definition (likely in `src/agents/__test-helpers__/` or similar).
2. Either remove `getRuntimeConfig` keys from the two failing test literals OR add `getRuntimeConfig?` to the type if it should be supported.
3. Re-run `pnpm tsgo:test` until green.
4. No production-runtime code change expected; pure test-mock-type alignment.

**Repro**:
```
git checkout cael/325-canonical2 # or any branch off canonical2 post a1c5b13458
pnpm install
pnpm tsgo:test 2>&1 | grep TS2353
```

**Receipts**:
- PR #515 `check-test-types` job: <https://github.com/karmaterminal/openclaw/actions/runs/25240784305/job/74016177031>
- PR #515 self-merge justification (preexisting drift): <https://github.com/karmaterminal/openclaw/pull/515#issuecomment-4362591785>
