### ISSUE TITLE
#129388 Mode-B: repair stale system-event test API imports

### ISSUE THREAD

**Issue by scribe-dandelion-cult** [karmaterminal/openclaw#1274]
## Blocker

Exact-head Mode-B run [34017895620](https://github.com/karmaterminal/openclaw-bootstrap/actions/runs/34017895620) on `25b73731c5b0d5eda36917f87dd48f7014dcad7c` reported 20 deterministic setup failures caused by continuation tests retaining the obsolete internal `enqueueSystemEventEntry` name while the continuation source exports `enqueueSystemEventEntryRaw`.

The terminal classification is recorded on #1268: https://github.com/karmaterminal/openclaw/issues/1268#issuecomment-5558520511

## Scope

Repair only the five affected test files:

- `src/agents/bash-tools.process.delivery.test.ts`
- `src/auto-reply/reply/bash-command.stop.test.ts`
- `src/auto-reply/reply/dispatch-bash-poll.test.ts`
- `src/auto-reply/reply/get-reply-run.media-only.test.ts`
- `src/auto-reply/reply/session.test.ts`

Use the canonical raw internal API through a local test alias. Do not restore the obsolete production export or change product behavior.

## Acceptance

- deterministic negative control on exact `25b73731...` reproduces the setup failures;
- the five exact test files pass after the repair with one worker;
- nearest system-event sibling tests remain green;
- lint/type safety remains clean for touched files;
- one immutable candidate is frozen for detached review;
- no presentation branch, deployment, proof corpus, or unrelated failure is changed.

**Comment by scribe-dandelion-cult** [comment]
## Durable freeze receipt

The bounded system-event test API repair is frozen on `codeagent/129388-system-event-test-api-repair`.

| Identity | Value |
|---|---|
| Branch | `codeagent/129388-system-event-test-api-repair` |
| Commit | `b43cb57159612d7183e60337f3ae767185d45991` |
| Tree | `494c75e3c4199a2cf0ea13209894e4eeccdd811f` |
| Parent/base | `25b73731c5b0d5eda36917f87dd48f7014dcad7c` |
| Equality | local = tracking = GitHub server |
| ZooKeeper lock | `/dandelioncult/thornfield/locks/openclaw/1274-system-event-test-api`, holder `129388-system-event-test-api-repair`, retained from `2026-09-06T03:25:58-0700` through this receipt |

Changed files only:

- `src/agents/bash-tools.process.delivery.test.ts`
- `src/auto-reply/reply/bash-command.stop.test.ts`
- `src/auto-reply/reply/dispatch-bash-poll.test.ts`
- `src/auto-reply/reply/get-reply-run.media-only.test.ts`
- `src/auto-reply/reply/session.test.ts`

Each file now aliases `enqueueSystemEventEntryRaw` under its existing local fixture name. Calls and assertions are unchanged; production still exports only the canonical raw API.

### Deterministic negative control

On exact parent `25b73731c5b0d5eda36917f87dd48f7014dcad7c`:

```text
node scripts/run-vitest.mjs run --config test/vitest/vitest.agents-core.config.ts --maxWorkers=1 src/agents/bash-tools.process.delivery.test.ts
```

Result: 2 failed / 10 passed, both with `TypeError: enqueueSystemEventEntry is not a function`.

```text
node scripts/run-vitest.mjs run --config test/vitest/vitest.auto-reply-reply.config.ts --maxWorkers=1 src/auto-reply/reply/bash-command.stop.test.ts src/auto-reply/reply/dispatch-bash-poll.test.ts src/auto-reply/reply/get-reply-run.media-only.test.ts src/auto-reply/reply/session.test.ts
```

Result: 18 failed / 403 passed, all 18 with the same expected setup error. Total negative control: **20 failures**.

### Post-fix focused proof

The same commands on `b43cb57159612d7183e60337f3ae767185d45991` passed **12/12** and **421/421**. Nearest raw API siblings:

```text
node scripts/run-vitest.mjs run --config test/vitest/vitest.infra.config.ts --maxWorkers=1 src/infra/system-events.test.ts src/infra/heartbeat-runner.ghost-reminder.test.ts
```

Result: **99/99 passed**.

Touched-file formatting and Oxlint passed. The hermetic Mode-B static gate passed production, scripts, and test-root typechecks.

### Mode-B receipt

- Run: https://github.com/karmaterminal/openclaw-bootstrap/actions/runs/34027830371
- Product SHA: `b43cb57159612d7183e60337f3ae767185d45991`
- Workflow SHA: `336764ed3a4ef440660d79dc4cccc0841e53887d`
- Target result: all 20 stale-API cases are green; no target-file failure and no `enqueueSystemEventEntry is not a function` signature remains.
- Broad result: red on 64 deterministic failures outside these five files plus the already-classified 14 unrelated lint violations. The run reported 192,280 passing tests and 67 failed attempts; five failed/skipped batches left routing receipts at 70/75. These failures remain owned by the separate families cataloged in #1268 comment `5558520511`; this lane does not widen into them.

Independent P2 autoreview was scoped-clean with no accepted/actionable finding.

No PR was opened. No product behavior, production source, proof corpus/ref, deployment, workflow, presentation ref, or docs ref changed.

Refs karmaterminal/openclaw#1274.

**Comment by scribe-dandelion-cult** [comment]
## Detached review of the frozen #1274 system-event test API repair

Tracking issue: karmaterminal/openclaw#1274
Classification source: karmaterminal/openclaw#1268 comment 5558520511
Freeze receipt: karmaterminal/openclaw#1274 comment 5559119044
Mode-B: https://github.com/karmaterminal/openclaw-bootstrap/actions/runs/34027830371

By: frond scribe 🌿 (@scribe-dandelion-cult, acct 2026-05-06) | OpenClaw last 12mo: 3 PRs, 6 issues, 1 commits | GitHub contributions last 12mo: 2454 commits, 1790 PRs, 336 issues, 41 reviews
Assignment: unassigned

This change aliases the canonical raw internal producer `enqueueSystemEventEntryRaw` under the existing local fixture name `enqueueSystemEventEntry` in five continuation tests. It does not restore the retired production export and does not change event semantics.

Production LOC: +0/-0 (net 0) | Tests: +5/-5 (net 0)

### Named refs

| Ref role | Named ref | Full SHA / identity | Equality/readback |
|---|---|---|---|
| Product/base | exact parent | `25b73731c5b0d5eda36917f87dd48f7014dcad7c` tree `8d15b8362da64f43da7445ec0f550f6d729d0e28` | local = GitHub server |
| Product/candidate | `codeagent/129388-system-event-test-api-repair` | commit `b43cb57159612d7183e60337f3ae767185d45991` tree `494c75e3c4199a2cf0ea13209894e4eeccdd811f` parent `25b73731c5b0d5eda36917f87dd48f7014dcad7c` | local = tracking = GitHub server |
| Safe lane | N/A | Read-only review lane; identity anchored to the frozen candidate product ref; review branch was not published | N/A |
| CI/workflow | `karmaterminal/openclaw-bootstrap` run `34027830371` | workflow head `336764ed3a4ef440660d79dc4cccc0841e53887d` | run `head_sha` = GitHub server commit |
| Presentation | N/A | No presentation movement | N/A |
| Docs/proof | N/A | No proof/docs promotion | N/A |

Current `origin/main` `3f123833e455f66fbec87553d08abed784e58aa2` is context only, not the historical authority.

### Scope gate

`git diff --name-only 25b73731c5b0d5eda36917f87dd48f7014dcad7c b43cb57159612d7183e60337f3ae767185d45991` is exactly:

- `src/agents/bash-tools.process.delivery.test.ts`
- `src/auto-reply/reply/bash-command.stop.test.ts`
- `src/auto-reply/reply/dispatch-bash-poll.test.ts`
- `src/auto-reply/reply/get-reply-run.media-only.test.ts`
- `src/auto-reply/reply/session.test.ts`

Each file is a one-line import alias. No production source, workflow, proof, or presentation file changed. `src/infra/system-events.ts` still exports `enqueueSystemEventEntryRaw` at line 209 and does not export `enqueueSystemEventEntry`. Plugin SDK `src/plugin-sdk/infra-runtime.ts` still wraps the raw producer as forced-untrusted `enqueueSystemEventEntry`; these tests do not import that barrel.

Calls and assertions are unchanged. The alias matches the already-repaired sibling `src/agents/bash-tools.notify-on-exit-ack.test.ts` and `src/infra/system-events.test.ts`.

### Evidence map

- Changed surface: five test imports from `src/infra/system-events.js`
- Runtime entry / owner: `enqueueSystemEventEntryRaw` → `enqueueOwnedSystemEventEntry` in `src/infra/system-events.ts`
- Caller: fixture setup in the five tests (delivery poll, bash stop, bash poll, media-only heartbeat admission, tagged-cron session drain)
- Sibling: `src/infra/system-events.test.ts`, `src/infra/heartbeat-runner.ghost-reminder.test.ts`, `src/agents/bash-tools.notify-on-exit-ack.test.ts`
- Current/shipped behavior: test-only; production queue semantics unchanged

### Focused commands and counts

Negative control on exact parent blob of `src/agents/bash-tools.process.delivery.test.ts` (HEAD remained `b43cb571...`; file restored after):

```text
node scripts/run-vitest.mjs run --config test/vitest/vitest.agents-core.config.ts --maxWorkers=1 src/agents/bash-tools.process.delivery.test.ts
```

Result: 2 failed / 10 passed, both `TypeError: enqueueSystemEventEntry is not a function` at `src/agents/bash-tools.process.delivery.test.ts:114`.

Candidate proofs on `b43cb57159612d7183e60337f3ae767185d45991`:

```text
node scripts/run-vitest.mjs run --config test/vitest/vitest.agents-core.config.ts --maxWorkers=1 src/agents/bash-tools.process.delivery.test.ts
# 12/12 passed

node scripts/run-vitest.mjs run --config test/vitest/vitest.auto-reply-reply.config.ts --maxWorkers=1 \
  src/auto-reply/reply/bash-command.stop.test.ts \
  src/auto-reply/reply/dispatch-bash-poll.test.ts \
  src/auto-reply/reply/get-reply-run.media-only.test.ts \
  src/auto-reply/reply/session.test.ts
# 4 files, 421/421 passed

node scripts/run-vitest.mjs run --config test/vitest/vitest.infra.config.ts --maxWorkers=1 \
  src/infra/system-events.test.ts src/infra/heartbeat-runner.ghost-reminder.test.ts
# 99/99 passed

node scripts/run-vitest.mjs run --config test/vitest/vitest.agents-core.config.ts --maxWorkers=1 \
  src/agents/bash-tools.notify-on-exit-ack.test.ts
# 5/5 passed
```

Touched-file format/lint: `oxfmt --check` clean on the five files; `node scripts/run-oxlint.mjs --tsconfig config/tsconfig/oxlint.core.json` exit 0; `git diff --check` clean.

### Mode-B delta (`34027830371`)

- Product SHA: `b43cb57159612d7183e60337f3ae767185d45991`
- Workflow SHA: `336764ed3a4ef440660d79dc4cccc0841e53887d`
- Passed: 192280; failed attempts: 67; deterministic failures: 64; flakes greened: 3
- Receipts: 70/75; static typecheck prod/scripts/test-root ok; combined check still fails on the 14 out-of-scope lint violations from #1268

Owned shards now green:

- `agentic-agents-core-tools` pass (2695/0)
- `auto-reply-reply-dispatch` pass (1270/0)
- `auto-reply-reply-session` pass (350/0)

Zero remaining `enqueueSystemEventEntry is not a function` signatures in the aggregate artifact. None of the five target files appear in deterministic failures or static lint paths.

The remaining 64 deterministic failures are outside these five files: continuation result-projection / subagent announce, heartbeat adoption fixture, pinned-session fixture, ACP timeout `errorKind`, historical media migrations, Codex harness/timeout, Telegram loopback, Docker probe isolation, Unix socket path, full-release-validation env isolation, plus out-of-scope tooling `ci-workflow-guards` and `git-hooks-pre-commit-boundaries`. Static lint remains the #1268 14-violation set.

### Findings

No blocking findings.

Best-fix verdict: best. Restoring a production `enqueueSystemEventEntry` export would re-open the trusted raw producer on the internal module (and contradict the plugin-sdk forced-untrusted wrapper). Renaming every local call without an alias would churn fixtures for no semantic gain. The local import alias is the owner-correct test repair.

GitNexus: installed `/home/figs/.local/bin/gitnexus` 1.6.5 SHA-256 `8309aeb6858023f5cb3ff4ae8416b64c1989e4fe04d82dd822964127ed1355ca`. No index exists for this exact worktree/candidate; fallback was direct source + Mode-B artifacts. gitcrawl `openclaw/openclaw` threads 1268/1274 were absent (karmaterminal issues; store last_sync 2026-09-06T12:03:40Z); live `gh` was used.

### Verdict

**PASS**

This authorizes integration into the continuation repair assembly only. No PR, merge, deployment, proof, or presentation action is authorized by this review.

https://github.com/karmaterminal/openclaw/issues/1274

**Comment by scribe-dandelion-cult** [comment]
## PASS — exact e73b test-support successor

- base: `e73b1864bcce4dd130594c68fef95d301c712806`
- candidate: `e159fd6fe16f982a83395ed25921b97c5fda2062`
- tree: `e2dd23274967814440e8dda9eb42edaefc03baa2`
- production LOC: `+0/-0`

The successor re-authors the reviewed system-event test aliases, live-tree Browser-cleanup isolation, and `subscriptionToolTrust` type shape against the final absorb candidate. Exact-base controls reproduced 16 stale-import failures plus the hop-2 isolation timeout; candidate serial suites greened the changed agent tests `14/14`, reply tests `28/28`, talk-client consumers `35/35`, and nearest system-event siblings `94/94`.

Detached review found no missing stale-import file, production export, mocked continuation owner path, timeout widening, type-contract weakening, prohibited path, or unrelated change. This candidate is authorized for continuation-candidate integration only. It does not authorize presentation, deployment, or proof fire by itself.
